name: Send Slack notification if workflow fails
description: Send Slack notification if workflow fails

inputs:
  slack_channel_id:
    description: Slack channel ID
    required: true
  slack_token:
    description: Slack token
    required: true

runs:
  using: composite
  steps:
    - name: Send Slack notification if workflow fails
      uses: someimportantcompany/github-actions-slack-message@a975b440de2bcef178d451cc70d4c1161b5a30cd
      with:
        channel: ${{ inputs.slack_channel_id }}
        bot-token: ${{ inputs.slack_token }}
        color: failure
        text: The last '${{ github.workflow }}' run failed. See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
